version: '3.8'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
    ports:
      - "2306:80"
    depends_on:
      - db

volumes:
  db_data:
