version: '3.8'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
