version: '3.8'
services:
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - client
  client:
    build: ./client
    volumes:
      - ./client:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      GMAIL_APP_USER: ${GMAIL_APP_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      - db
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "2306:80"
    depends_on:
      - db

volumes:
  db_data:
