import { NotificationProvider } from "../../context/notification";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Footer from "./components/footer";
import { UserProvider } from "../../context/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoginPage = typeof window !== "undefined" && window.location.pathname === "/login"; 

  return (
    <UserProvider>
      <NotificationProvider>
        <html lang="en">
          <body>
            {!isLoginPage && <Nav />}  
            {children}
            <Footer />
          </body>
        </html>
      </NotificationProvider>
    </UserProvider>
  );
}

