// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Footer from "./components/footer";
import { UserProvider } from "../../context/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoginPage = typeof window !== "undefined" && window.location.pathname === "/login"; // ログインページかどうかを判定

  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>
          {!isLoginPage && <Nav />}  {/* ログインページではナビゲーションを非表示 */}
          {children}
          <Footer />
        </body>
      </html>
    </UserProvider>
  );
}
